### ISSUE TITLE
Moving items to the same place

### ISSUE THREAD

**Issue by trickeydan** [srobo/tools#8]
The `inv-mv` script crashes when one of the parts being moved is already in that location. It does not move any of the items and gives no useful output.

Ideally this should accept the move (with a warning) as we are defining the known location of the item.

**Comment by PeterJCLaw** [comment]
For reference, here's an example of the error output when doing this:
```
fatal: can not move directory into itself, source=koolertron-barcode-scanner-sr9M2M, destination=koolertron-barcode-scanner-sr9M2M
Traceback (most recent call last):
  File "/home/srobo/tools/sr/tools/cli/__init__.py", line 52, in main
    args.func(args)
  File "/home/srobo/tools/sr/tools/cli/inv_mv.py", line 44, in command
    subprocess.check_call(['git', 'mv'] + paths + ['.'])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'mv', '/home/srobo/inventory/koolertron-barcode-scanner-sr9M2M', '.']' returned non-zero exit status 128
Command '['git', 'mv', '/home/srobo/inventory/koolertron-barcode-scanner-sr9M2M', '.']' returned non-zero exit status 128
```
